"""Export a Wireshark Lua dissector from DBC signal definitions.

Two things make a generated dissector fail to load, and both were present
before: ``bit32`` was removed in Lua 5.3 (Wireshark 4.4 ships 5.4), and
``Field.new`` must be called at load time, not inside the dissector function.
The extractor below is therefore written in plain arithmetic that runs
unchanged on Lua 5.1 through 5.4, and the field accessors are created at file
scope.
"""
from __future__ import annotations

import re

from canlab.core.dbc_manager import dbc_frame_id, frame_id_int, norm_signal

# Lua numbers are IEEE doubles: integers stay exact to 2^53.
MAX_SIGNAL_BITS = 53


def _lua_string(text) -> str:
    """Escape a value for a Lua double-quoted string."""
    return (str(text or "")
            .replace("\\", "\\\\").replace('"', '\\"')
            .replace("\n", " ").replace("\r", " "))


def _lua_safe(name: str, used: set | None = None) -> str:
    """A legal, unique Lua identifier for ``name``."""
    safe = re.sub(r"[^0-9A-Za-z_]", "_", str(name or "sig"))
    if not safe or safe[0].isdigit():
        safe = "_" + safe
    if used is None:
        return safe
    # "Speed-L" and "Speed_L" both reduce to Speed_L; keep them distinct.
    candidate, n = safe, 2
    while candidate in used:
        candidate = f"{safe}_{n}"
        n += 1
    used.add(candidate)
    return candidate


_EXTRACTOR = '''
-- Bit extraction in plain arithmetic: bit32 was removed in Lua 5.3 and the
-- 5.3+ operators are a syntax error on 5.1/5.2, so neither can appear here.
local function get_bit(buf, byte_i, bit_i)
    if byte_i >= buf:len() then return 0 end
    local b = buf(byte_i, 1):uint()
    return math.floor(b / (2 ^ bit_i)) % 2
end

function canlab_extract_bits(buf, start_bit, length, byte_order, is_signed)
    local result = 0
    if byte_order == "little" then
        -- Little-endian: start_bit is the LSB, growing towards higher bits.
        for i = 0, length - 1 do
            local pos = start_bit + i
            local bit = get_bit(buf, math.floor(pos / 8), pos % 8)
            result = result + bit * (2 ^ i)
        end
    else
        -- Big-endian (Motorola sawtooth), matching the DBC @0 convention.
        local pos = start_bit
        for _ = 1, length do
            local bit = get_bit(buf, math.floor(pos / 8), pos % 8)
            result = result * 2 + bit
            if pos % 8 == 0 then pos = pos + 15 else pos = pos - 1 end
        end
    end
    if is_signed and result >= 2 ^ (length - 1) then
        result = result - 2 ^ length
    end
    return result
end
'''


def signals_to_lua_dissector(signal_defs: list[dict]) -> str:
    """Generate a Wireshark post-dissector for these signals.

    Install by copying the file into ``~/.config/wireshark/plugins/``, or load
    it with Analyze > Run Lua Script.

    Raises ValueError for a signal wider than a Lua number can hold exactly.
    """
    messages: dict[int, dict] = {}
    for raw in signal_defs:
        sig = norm_signal(raw)
        if sig["length"] > MAX_SIGNAL_BITS:
            raise ValueError(
                f"Signal {sig.get('signal_name')!r} is {sig['length']} bits; "
                f"Lua numbers only hold {MAX_SIGNAL_BITS} bits exactly.")
        fid = frame_id_int(sig)
        msg = messages.setdefault(fid, {
            "name": sig.get("message_name") or f"MSG_{sig['message_id']}",
            "extended": bool(dbc_frame_id(sig) & 0x80000000),
            "signals": [],
            "used": set(),
        })
        sig["_lua"] = _lua_safe(sig.get("signal_name"), msg["used"])
        msg["signals"].append(sig)

    lines = [
        "-- Auto-generated by CanLab. Wireshark 3.x-4.x (Lua 5.1-5.4).",
        "",
        'local canlab_proto = Proto("CANLAB_DBC", "CanLab DBC Dissector")',
        "",
        "-- Field extractors must be created at load time, not per packet.",
        'local can_id_field = Field.new("can.id")',
        'local can_data_field = Field.new("can.data")',
        "",
        "-- Field definitions",
    ]

    field_vars = []
    for fid, msg in sorted(messages.items()):
        for sig in msg["signals"]:
            var = f"f_{fid:X}_{sig['_lua']}"
            field_vars.append(var)
            label = _lua_string(sig.get("signal_name"))
            unit = _lua_string(sig.get("unit", ""))
            desc = _lua_string(sig.get("description") or sig.get("signal_name"))
            title = f"{label} ({unit})" if unit else label
            lines.append(
                f'local {var} = ProtoField.double("canlab_dbc.{fid:X}.{sig["_lua"]}", '
                f'"{title}", nil, "{desc}")')

    lines += [
        "",
        "canlab_proto.fields = {" + ", ".join(field_vars) + "}",
        _EXTRACTOR,
        "function canlab_proto.dissector(buffer, pinfo, tree)",
        "    local can_id_fi = can_id_field()",
        "    if not can_id_fi then return end",
        "    local can_id = can_id_fi.value",
        "",
        "    -- Signal offsets are relative to the CAN payload, not the capture",
        "    -- buffer, so dissect the data field as its own tvb.",
        "    local data_buf = buffer",
        "    local can_data_fi = can_data_field()",
        "    if can_data_fi then data_buf = can_data_fi.range:tvb() end",
        "",
        '    local subtree = tree:add(canlab_proto, buffer(), '
        '"CanLab: " .. string.format("0x%X", can_id))',
        "",
    ]

    for fid, msg in sorted(messages.items()):
        lines.append(f'    if can_id == 0x{fid:X} then  -- {msg["name"]}')
        lines.append(f'        subtree:append_text(" ({_lua_string(msg["name"])})")')

        selector = next((s for s in msg["signals"] if s.get("mux_role") == "M"), None)
        if selector is not None:
            lines.append(
                f'        local mux = canlab_extract_bits(data_buf, {selector["start_bit"]}, '
                f'{selector["length"]}, "{selector["byte_order"]}", false)')

        for sig in msg["signals"]:
            var = f"f_{fid:X}_{sig['_lua']}"
            indent = "        "
            mux_value = sig.get("mux_value")
            if mux_value is not None and selector is not None:
                # Multiplexed signals are only present for their selector value.
                lines.append(f"        if mux == {int(mux_value)} then")
                indent = "            "
            lines.append(
                f'{indent}local raw_{sig["_lua"]} = canlab_extract_bits(data_buf, '
                f'{sig["start_bit"]}, {sig["length"]}, "{sig["byte_order"]}", '
                f'{str(sig["value_type"] == "signed").lower()})')
            lines.append(
                f'{indent}subtree:add({var}, raw_{sig["_lua"]} * {sig["scale"]} '
                f'+ {sig["offset"]})')
            if mux_value is not None and selector is not None:
                lines.append("        end")
        lines.append("    end")
        lines.append("")

    lines += [
        "end",
        "",
        "-- Register on CAN frames",
        'local can_table = DissectorTable.get("can.subdissector")',
        "if can_table then",
        "    can_table:add_for_decode_as(canlab_proto)",
        "else",
        "    register_postdissector(canlab_proto)",
        "end",
    ]
    return "\n".join(lines) + "\n"
